#!/bin/bash

ffmpeg -f x11grab -video_size 1280x1024 -framerate 24 -i -f alsa -vf scale=1280x720 -c:v h264 -g 24 -b:v 2M -preset ultrafast -c:a aac -pix_fmt yuv420p -f flv "rtmp://live-lax.twitch.tv/app/*****afteryoueditinkeyrenametojuststartStream.sh******"